version: "3.8"

services:

  rabbitmq_mqtt:
    build: ./rabbitmq_mqtt
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
       


  # mosquitto:
  #   image: eclipse-mosquitto:2
  #   port:
  #     - 1883:1883
  #   volumes:
  #     - ./mosquitto/config:/mosquitto/config
  