version: "3.8"

services:
  subscriber:
    build: ./sensors
    environment:
      - RABBITMQ_URI=amqp://mqtt:mqtt@rabbitmq_mqtt/
    env_file:
      - .env
    depends_on:
      - rabbitmq_mqtt

  rabbitmq_mqtt:
    build: ./rabbitmq_mqtt
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=mqtt
      - RABBITMQ_DEFAULT_PASS=mqtt
    volumes:
      - ./rabbitmq_mqtt/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
