version: "3.8"

services:
  subscriber:
    build: .
    image: temperature_subscriber
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_ORG
      - INFLUXDB_BUCKET
      - INFLUXDB_TOKEN
      - RABBIT_MQTT_EXCHANGE_NAME
      - RABBITMQ_URI=amqp://mqtt:mqtt@rabbitmq/
    depends_on:
      - rabbitmq
      - influxdb

  rabbitmq:
    build: ./rabbitmq_mqtt
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=mqtt
      - RABBITMQ_DEFAULT_PASS=mqtt
      - RABBITMQ_EXCHANGE_NAME

  influxdb:
    image: influxdb:2.7
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=mqtt
      - DOCKER_INFLUXDB_INIT_PASSWORD=mqtt-password
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    ports:
      - 127.0.0.1:8086:8086
    volumes:
      - influx_data:/var/lib/influxdb2

volumes:
  influx_data:
